import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const dist = fileURLToPath(new URL('../dist/', import.meta.url));

async function filesUnder(directory, prefix = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async entry => {
      const relative = path.posix.join(prefix, entry.name);
      return entry.isDirectory() ? filesUnder(path.join(directory, entry.name), relative) : [relative];
    })
  );
  return files.flat();
}

// LLO programs are large and fetched on demand; the worker caches them on first use instead of at install.
const assets = (await filesUnder(dist)).filter(file => file !== 'sw.js' && !file.startsWith('llo/')).sort();
const hash = createHash('sha256');
for (const file of assets) {
  hash.update(file);
  hash.update(await readFile(path.join(dist, file)));
}
const cacheName = `tpu-visualizer-${hash.digest('hex').slice(0, 16)}`;

const worker = `// Generated by scripts/generate-sw.mjs after each production build.
const CACHE_PREFIX = 'tpu-visualizer-';
const CACHE_NAME = ${JSON.stringify(cacheName)};
const ASSETS = ${JSON.stringify(assets)};
const scopedUrl = path => new URL(path, self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS.map(scopedUrl)))
  );
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME).map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;

  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match(scopedUrl('index.html'), { ignoreVary: true })));
    return;
  }

  // Module scripts send an Origin header while install-time precache requests may not.
  // All entries are same-origin, so ignore Vary when matching these cached files.
  event.respondWith(
    caches.match(request, { ignoreVary: true }).then(
      cached =>
        cached ||
        fetch(request).then(response => {
          if (response.ok && url.pathname.includes('/llo/')) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then(cache => cache.put(request, copy));
          }
          return response;
        })
    )
  );
});
`;

await writeFile(path.join(dist, 'sw.js'), worker);
console.log(`Generated sw.js: ${assets.length} offline assets (${cacheName})`);
