import index from './llo-index.json';

// Verified final-bundle programs, one file per HLO instruction, generated by scripts/select_llo_examples.py.
// The text lives under public/llo and is fetched when chosen; the service worker caches it on first use.
export interface LloExample {
  id: string;
  topology: string;
  example: string;
  instruction: string;
  opcode: string;
  bundles: number;
  default: boolean;
  hloExample: string | null;
  load: () => Promise<string>;
}

export const lloExamples: LloExample[] = index.map(entry => ({
  ...entry,
  load: () =>
    fetch(`${import.meta.env.BASE_URL}llo/${entry.id}.llo`).then(response => {
      if (!response.ok) throw new Error(`Could not load ${entry.id} (${response.status})`);
      return response.text();
    })
}));

export const lloTopologies = [...new Set(lloExamples.map(item => item.topology))];

// Accepts a program id, or an older <topology>/<example> id that resolves to that example's default program.
export const findLloExample = (id: string | null) =>
  lloExamples.find(item => item.id === id) ?? lloExamples.find(item => item.default && `${item.topology}/${item.example}` === id) ?? null;
